#20220520T0736590136Z
New-Alias -Name Write-Errorlog -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-Scripts\Write-Errorlog_20220517-111618.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Win10Debloater -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Win10Debloater_20210609-85507.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Show-PercentPoints -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-Scripts\Show-PercentPoints_20220517-82537.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Set-SuccessfullTested -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-Scripts\Set-SuccessfullTested_20220518-65433.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Set-MySettings -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-Scripts\Set-MySettings_20220516-130815.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Set-ISESnippetForCreatingISESnippets -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-Scripts\Set-ISESnippetForCreatingISESnippets_20220517-82332.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Replace-SpacesInNames -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-System\Replace-SpacesInNames_20220518-70806.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Replace-SignWithWord -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-System\Replace-SignWithWord_20220518-70719.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Open-HelpWebsite -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Create-Help\Open-HelpWebsite_20220517-60318.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name MySettings -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\MySettings.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name MakeSure-PathExists -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-System\MakeSure-PathExists_20220518-70526.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name MakeSure-FolderExists -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-System\MakeSure-FolderExists_20220325-135201.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Make-Space -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-System\Make-Space_20220512-123242.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Keep-OnlyYoungestFile -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-System\Keep-OnlyYoungestFile_20220518-70342.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Get-FilesFrmFolderSrtdByLstWrTmUTC -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-System\Get-FilesFrmFolderSrtdByLstWrTmUTC_20220330-101047.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Delete-FilesOlderThan -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-System\Delete-FilesOlderThan_20220518-65107.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Create-HelpWebsite -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Create-Help\Create-HelpWebsite_20220517-91833.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Create-HelpTxtsComplet -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Create-Help\Create-HelpTxtsComplet_20220517-95844.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Create-HelpTxtFile -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Create-Help\Create-HelpTxtFile_20220517-91742.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Cleanup-System -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-System\Cleanup-System_20220520-73600.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name AuswertungStoerungsCSVsKompletterOrdner -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\AuswertungStoerungsCSV\AuswertungStoerungsCSVsKompletterOrdner_20210802-193112.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name AuswertungStoerungsCSV-GUI -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\AuswertungStoerungsCSV\AuswertungStoerungsCSV-GUI_20210903-130745.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name AuswertungStoerungsCSV -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\AuswertungStoerungsCSV\AuswertungStoerungsCSV_20210731-143927.ps1' -Option AllScope,ReadOnly -Force -Scope Global
New-Alias -Name Analyse-Errorlog -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\Manage-Scripts\Analyse-Errorlog_20220518-65651.ps1' -Option AllScope,ReadOnly -Force -Scope Global
[string](New-Variable -Name strAliasMask -Value '^[^_\.]*' -Option AllScope,ReadOnly -Force -Scope Global)
[string](New-Variable -Name strLstWrtTmUTCMask -Value '_\d{8}-\d{5,6}$' -Option AllScope,ReadOnly -Force -Scope Global)
[string](New-Variable -Name strPathScripts -Value 'C:\Users\m.bartscher\OneDrive - promatic Automatisierungssysteme GmbH\DASI\Skripte\Powershell\Working\' -Option AllScope,ReadOnly -Force -Scope Global)
if(-not($strMySettingsScriptName)){[string](New-Variable -Name strMySettingsScriptName -Value 'MySettings' -Option AllScope,Constant -Force -Scope Global)}
[string](New-Variable -Name strBreak -Value "`n" -Option AllScope,ReadOnly -Force -Scope Global)
[string](New-Variable -Name strTab -Value "`t" -Option AllScope,ReadOnly -Force -Scope Global)